"""Canonical data contracts for bot logging."""

from __future__ import annotations

SIDE_SNAPSHOT_COLUMNS = [
    "match_id",
    "market_id",
    "condition_id",
    "market_name",
    "market_type",
    "label_market_bucket",
    "current_game_number",
    "series_type",
    "side",
    "token_id",
    "opposing_token_id",
    "received_at_utc",
    "received_at_ns",
    "game_time_sec",
    "book_received_at_utc",
    "book_received_at_ns",
    "book_age_ms",
    "book_best_bid",
    "book_best_ask",
    "book_bid_size",
    "book_ask_size",
    "book_mid",
    "book_spread",
    "settled_win",
    "radiant_win",
    "side_is_radiant",
    "yes_is_radiant",
    "hold_to_settlement_pnl_per_share",
    "hold_to_settlement_roi",
    "radiant_lead",
    "radiant_score",
    "dire_score",
    "radiant_net_worth",
    "dire_net_worth",
    "net_worth_diff",
    "yes_team",
    "no_team",
    "steam_radiant_team",
    "steam_dire_team",
    "steam_side_mapping",
    "outcome_source",
    "market_source_file",
    "dataset_version",
    "lobby_id",
    "league_id",
    "server_steam_id",
    "building_state",
    "tower_state",
    "roshan_respawn_timer",
    "stream_delay_s",
    "source_update_age_sec",
    "data_source",
    "spectators",
    "game_over",
    "series_id",
    "radiant_team",
    "dire_team",
    "radiant_team_id",
    "dire_team_id",
    "schema_version",
    "source_file",
    "series_type_market",
    "yes_token_id",
    "no_token_id",
    "confidence",
    "yes_won",
    "no_won",
    "asset_id",
    "book_schema_version",
    "book_source_file",
]


DECISION_COLUMNS = [
    "decision_id",
    "strategy_name",
    "match_id",
    "market_id",
    "token_id",
    "side",
    "received_at_utc",
    "received_at_ns",
    "game_time_sec",
    "ask",
    "bid",
    "book_age_ms",
    "signal",
    "reason",
    "score",
    "settled_win",
    "paper_pnl_per_share",
]


LIVE_BOOK_COLUMNS = [
    "book_event_id",
    "asset_id",
    "received_at_utc",
    "received_at_ns",
    "best_bid",
    "best_ask",
    "bid_size",
    "ask_size",
    "mid",
    "spread",
    "request_start_ns",
    "refresh_latency_ns",
    "source",
]


LIVE_GAME_COLUMNS = [
    "received_at_utc",
    "received_at_ns",
    "match_id",
    "lobby_id",
    "league_id",
    "server_steam_id",
    "game_time_sec",
    "radiant_lead",
    "radiant_score",
    "dire_score",
    "building_state",
    "tower_state",
    "stream_delay_s",
    "source_update_age_sec",
    "data_source",
    "spectators",
    "game_over",
    "radiant_team",
    "dire_team",
    "radiant_team_id",
    "dire_team_id",
    "radiant_net_worth",
    "dire_net_worth",
    "net_worth_diff",
    "raw_json",
]
